### ISSUE TITLE
Newly installed bot not working

### ISSUE THREAD

**Issue by byadems** [souravkl11/raganork-md#130]
How many different numbers have I tried, the result is the same and I'm not setting up a bot for the first time. Can you fix the error?

Failed to start, error:
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at restoreSession (/rgnk/lib/Session.js:1:15028)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async /rgnk/index.js:1:36818

**Comment by byadems** [comment]
**After the last update, these errors have now started to appear...**

raganork-md v3.0.0
(node:1) Warning: Accessing non-existent property 'avMix' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Restoring session
Connected to host server
BOT STARTED
Failed to decrypt message with any known session...
Session error:Error: Bad MAC Error: Bad MAC
at Object.verifyMAC (/rgnk/node_modules/libsignal/src/crypto.js:87:15)
at SessionCipher.doDecryptWhisperMessage (/rgnk/node_modules/libsignal/src/session_cipher.js:250:16)
at async SessionCipher.decryptWithSessions (/rgnk/node_modules/libsignal/src/session_cipher.js:147:29)
at async Object.905510910577.0 [as awaitable] (/rgnk/node_modules/libsignal/src/session_cipher.js:171:28)
at async _asyncQueueExecutor (/rgnk/node_modules/libsignal/src/queue_job.js:20:29)
Closing session: SessionEntry {
_chains: {
'BdYit6eha/LLzfIph1FsSMH4NPqm1eU0AX+ToVuwjSQ/': { chainKey: [Object], chainType: 1, messageKeys: {} }
},

**Comment by byadems** [comment]
After the last update, these errors have now started to appear...

raganork-md v3.0.0
(node:1) Warning: Accessing non-existent property 'avMix' of module exports inside circular dependency
(Use node --trace-warnings ... to show where the warning was created)
Restoring session
Connected to host server
BOT STARTED
Failed to decrypt message with any known session...
Session error:Error: Bad MAC Error: Bad MAC
at Object.verifyMAC (/rgnk/node_modules/libsignal/src/crypto.js:87:15)
at SessionCipher.doDecryptWhisperMessage (/rgnk/node_modules/libsignal/src/session_cipher.js:250:16)
at async SessionCipher.decryptWithSessions (/rgnk/node_modules/libsignal/src/session_cipher.js:147:29)
at async Object.19709007690.0 [as awaitable] (/rgnk/node_modules/libsignal/src/session_cipher.js:171:28)
at async _asyncQueueExecutor (/rgnk/node_modules/libsignal/src/queue_job.js:20:29)
Closing session: SessionEntry {
_chains: {
'BdYit6eha/LLzfIph1FsSMH4NPqm1eU0AX+ToVuwjSQ/': { chainKey: [Object], chainType: 1, messageKeys: {} }
},

**Comment by souravkl11** [comment]
> After the last update, these errors have now started to appear...
> 
> raganork-md v3.0.0 (node:1) Warning: Accessing non-existent property 'avMix' of module exports inside circular dependency (Use node --trace-warnings ... to show where the warning was created) Restoring session Connected to host server BOT STARTED Failed to decrypt message with any known session... Session error:Error: Bad MAC Error: Bad MAC at Object.verifyMAC (/rgnk/node_modules/libsignal/src/crypto.js:87:15) at SessionCipher.doDecryptWhisperMessage (/rgnk/node_modules/libsignal/src/session_cipher.js:250:16) at async SessionCipher.decryptWithSessions (/rgnk/node_modules/libsignal/src/session_cipher.js:147:29) at async Object.19709007690.0 [as awaitable] (/rgnk/node_modules/libsignal/src/session_cipher.js:171:28) at async _asyncQueueExecutor (/rgnk/node_modules/libsignal/src/queue_job.js:20:29) Closing session: SessionEntry { _chains: { 'BdYit6eha/LLzfIph1FsSMH4NPqm1eU0AX+ToVuwjSQ/': { chainKey: [Object], chainType: 1, messageKeys: {} } },

Please don't update if there is a "test" in update message, it's will be a test attempt

**Comment by souravkl11** [comment]
> How many different numbers have I tried, the result is the same and I'm not setting up a bot for the first time. Can you fix the error?
> 
> Failed to start, error: TypeError: Cannot convert undefined or null to object at Function.keys () at restoreSession (/rgnk/lib/Session.js:1:15028) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async /rgnk/index.js:1:36818

Problem fixed
