### ISSUE TITLE
Issues after issue

### ISSUE THREAD

**Issue by aasonacademy** [souravkl11/raganork-md#133]
after 2hours bot turn off automatically 
check the log file

raganork-md v3.0.0
Restoring session
Connected to host server
BOT STARTED
/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157
.then(() => reject(new boom_1.Boom('Timed Out', {
^
Error: Timed Out
at /rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157:32 {
data: {
stack: 'Error\n' +
' at promiseTimeout (/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:152:19)\n' +
' at waitForMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:100:61)\n' +
' at query (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:123:22)\n' +
' at assertSessions (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:193:34)\n' +
' at async /rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:349:17\n' +
' at async Object.transaction (/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:85:21)\n' +
' at async relayMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:262:9)\n' +
' at async Object.sendMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:521:17)\n' +
' at async /rgnk/index.js:1:25590'
},
isBoom: true,
isServer: false,
output: {
statusCode: 408,
payload: {
statusCode: 408,
error: 'Request Time-out',
message: 'Timed Out'
},
headers: {}
}
}
raganork-md v3.0.0
Restoring session
Connected to host server
BOT STARTED
/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157
.then(() => reject(new boom_1.Boom('Timed Out', {
^
Error: Timed Out
at /rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157:32 {
data: {
stack: 'Error\n' +
' at promiseTimeout (/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:152:19)\n' +
' at waitForMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:100:61)\n' +
' at query (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:123:22)\n' +
' at assertSessions (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:193:34)\n' +
' at async /rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:349:17\n' +
' at async Object.transaction (/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:85:21)\n' +
' at async relayMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:262:9)\n' +
' at async Object.sendMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:521:17)\n' +
' at async /rgnk/index.js:1:25590'
},
isBoom: true,
isServer: false,
output: {
statusCode: 408,
payload: {
statusCode: 408,
error: 'Request Time-out',
message: 'Timed Out'
},
headers: {}
}
}
raganork-md v3.0.0
Restoring session
Connected to host server
BOT STARTED
/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157
.then(() => reject(new boom_1.Boom('Timed Out', {
^
Error: Timed Out
at /rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157:32 {
data: {
stack: 'Error\n' +
' at promiseTimeout (/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:152:19)\n' +
' at waitForMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:100:61)\n' +
' at query (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:123:22)\n' +
' at assertSessions (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:193:34)\n' +
' at async /rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:349:17\n' +
' at async Object.transaction (/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:85:21)\n' +
' at async relayMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:262:9)\n' +
' at async Object.sendMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:521:17)\n' +
' at async /rgnk/index.js:1:25590'
},
isBoom: true,
isServer: false,
output: {
statusCode: 408,
payload: {
statusCode: 408,
error: 'Request Time-out',
message: 'Timed Out'
},
headers: {}
}
}
/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157
.then(() => reject(new boom_1.Boom('Timed Out', {
^
Error: Timed Out
at /rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157:32 {
data: {
stack: 'Error\n' +
' at promiseTimeout (/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:152:19)\n' +
' at waitForMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:100:61)\n' +
' at query (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:123:22)\n' +
' at assertSessions (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:193:34)\n' +
' at async /rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:349:17\n' +
' at async Object.transaction (/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:85:21)\n' +
' at async relayMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:262:9)\n' +
' at async Object.sendMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:521:17)\n' +
' at async /rgnk/index.js:1:25590'
},
isBoom: true,
isServer: false,
output: {
statusCode: 408,
payload: {
statusCode: 408,
error: 'Request Time-out',
message: 'Timed Out'
},
headers: {}
}
}

**Comment by aasonacademy** [comment]
> after 2hours bot turn off automatically check the log file
> 
> raganork-md v3.0.0 Restoring session Connected to host server BOT STARTED /rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157 .then(() => reject(new boom_1.Boom('Timed Out', { ^ Error: Timed Out at /rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157:32 { data: { stack: 'Error\n' + ' at promiseTimeout (/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:152:19)\n' + ' at waitForMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/socket.js💯61)\n' + ' at query (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:123:22)\n' + ' at assertSessions (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:193:34)\n' + ' at async /rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:349:17\n' + ' at async Object.transaction (/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:85:21)\n' + ' at async relayMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:262:9)\n' + ' at async Object.sendMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:521:17)\n' + ' at async /rgnk/index.js:1:25590' }, isBoom: true, isServer: false, output: { statusCode: 408, payload: { statusCode: 408, error: 'Request Time-out', message: 'Timed Out' }, headers: {} } } raganork-md v3.0.0 Restoring session Connected to host server BOT STARTED /rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157 .then(() => reject(new boom_1.Boom('Timed Out', { ^ Error: Timed Out at /rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157:32 { data: { stack: 'Error\n' + ' at promiseTimeout (/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:152:19)\n' + ' at waitForMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/socket.js💯61)\n' + ' at query (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:123:22)\n' + ' at assertSessions (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:193:34)\n' + ' at async /rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:349:17\n' + ' at async Object.transaction (/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:85:21)\n' + ' at async relayMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:262:9)\n' + ' at async Object.sendMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:521:17)\n' + ' at async /rgnk/index.js:1:25590' }, isBoom: true, isServer: false, output: { statusCode: 408, payload: { statusCode: 408, error: 'Request Time-out', message: 'Timed Out' }, headers: {} } } raganork-md v3.0.0 Restoring session Connected to host server BOT STARTED /rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157 .then(() => reject(new boom_1.Boom('Timed Out', { ^ Error: Timed Out at /rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157:32 { data: { stack: 'Error\n' + ' at promiseTimeout (/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:152:19)\n' + ' at waitForMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/socket.js💯61)\n' + ' at query (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:123:22)\n' + ' at assertSessions (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:193:34)\n' + ' at async /rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:349:17\n' + ' at async Object.transaction (/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:85:21)\n' + ' at async relayMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:262:9)\n' + ' at async Object.sendMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:521:17)\n' + ' at async /rgnk/index.js:1:25590' }, isBoom: true, isServer: false, output: { statusCode: 408, payload: { statusCode: 408, error: 'Request Time-out', message: 'Timed Out' }, headers: {} } } /rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157 .then(() => reject(new boom_1.Boom('Timed Out', { ^ Error: Timed Out at /rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157:32 { data: { stack: 'Error\n' + ' at promiseTimeout (/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:152:19)\n' + ' at waitForMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/socket.js💯61)\n' + ' at query (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:123:22)\n' + ' at assertSessions (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:193:34)\n' + ' at async /rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:349:17\n' + ' at async Object.transaction (/rgnk/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:85:21)\n' + ' at async relayMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:262:9)\n' + ' at async Object.sendMessage (/rgnk/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:521:17)\n' + ' at async /rgnk/index.js:1:25590' }, isBoom: true, isServer: false, output: { statusCode: 408, payload: { statusCode: 408, error: 'Request Time-out', message: 'Timed Out' }, headers: {} } }

Resolved
