### ISSUE TITLE
Bot crash

### ISSUE THREAD

**Issue by byadems** [souravkl11/raganork-md#167]
After the bot is updated, it pauses December and I encounter this error.

/rgnk/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:423
        quotedMsg = WAProto_1.proto.Message.fromObject({ [msgType]: quotedMsg[msgType] });
                                                                             ^
TypeError: Cannot read properties of undefined (reading 'undefined')
    at generateWAMessageFromContent (/rgnk/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:423:78)
    at generateWAMessage (/rgnk/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:477:53)
    at async Object.sendMessage (/rgnk/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:606:33)
    at async /rgnk/lib/Handler.js:1:34401
Node.js v20.1.0

**Comment by souravkl11** [comment]
Fixed, please try redeploying
