### ISSUE TITLE
Bot crash

### ISSUE THREAD

**Issue by byadems** [souravkl11/raganork-md#216]
I keep getting this error and the bot eventually shuts down on its own. When are you going to solve the problem?

Session error:Error: Bad MAC Error: Bad MAC
    at Object.verifyMAC (/rgnk/node_modules/libsignal/src/crypto.js:87:15)
    at SessionCipher.doDecryptWhisperMessage (/rgnk/node_modules/libsignal/src/session_cipher.js:250:16)
    at async SessionCipher.decryptWithSessions (/rgnk/node_modules/libsignal/src/session_cipher.js:147:29)
    at async 905312979999.0 [as awaitable] (/rgnk/node_modules/libsignal/src/session_cipher.js:171:28)
    at async _asyncQueueExecutor (/rgnk/node_modules/libsignal/src/queue_job.js:20:29)
Failed to decrypt message with any known session...

**Comment by Ayushdeveloper001** [comment]
Wrong session just rescan
