### ISSUE TITLE
Question: How to deploy in vps

### ISSUE THREAD

**Issue by ferhacks** [souravkl11/raganork-md#22]
when I want to start the bot from a vps this error comes out:

`TypeError: Cannot read properties of undefined (reading 'toString')
    at decryptString (C:\Users\Aiden\Documents\GitHub\raganork-md\node_modules\string-crypto\dist\index.js:1:563)
    at save (C:\Users\Aiden\Documents\GitHub\raganork-md\index.js:1:13538)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async start (C:\Users\Aiden\Documents\GitHub\raganork-md\index.js:1:39509)`

Any help?

**Comment by souravkl11** [comment]
> when I want to start the bot from a vps this error comes out:
> 
> `TypeError: Cannot read properties of undefined (reading 'toString') at decryptString (C:\Users\Aiden\Documents\GitHub\raganork-md\node_modules\string-crypto\dist\index.js:1:563) at save (C:\Users\Aiden\Documents\GitHub\raganork-md\index.js:1:13538) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async start (C:\Users\Aiden\Documents\GitHub\raganork-md\index.js:1:39509)`
> 
> Any help?

Edit the config.js and paste your session @ its place
