### ISSUE TITLE
Bot refuses to start - Please verify that the package.json has a valid "main" entry [fixed]

### ISSUE THREAD

**Issue by chocolaid** [souravkl11/raganork-md#222]
PM2][INFO] Log streaming apps id: 0, exit with Ctrl-C or will exit in 10secs
0|BOT  | raganork-md v4.0.0
0|BOT  | Failed to start, error:
0|BOT  |  Error: Cannot find module '/root/raganork-md/node_modules/cache-manager/dist/index.js'. Please verify that the package.json has a valid "main" entry
0|BOT  |     at tryPackage (node:internal/modules/cjs/loader:438:19)
0|BOT  |     at Module._findPath (node:internal/modules/cjs/loader:680:18)
0|BOT  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
0|BOT  |     at Hook._require.Module.require (/root/raganork-md/node_modules/require-in-the-middle/index.js:81:25)
0|BOT  |     at require (node:internal/modules/cjs/helpers:121:18)
0|BOT  |     at Object.<anonymous> (/root/raganork-md/node_modules/@whiskeysockets/baileys/lib/Store/make-cache-manager-store.js:6:25)
0|BOT  |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
0|BOT  |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
0|BOT  |     at Module.load (node:internal/modules/cjs/loader:1119:32)
0|BOT  |     at Module._load (node:internal/modules/cjs/loader:960:12) {
0|BOT  |   code: 'MODULE_NOT_FOUND',
0|BOT  |   path: '/root/raganork-md/node_modules/cache-manager/package.json',
0|BOT  |   requestPath: 'cache-manager'
0|BOT  | }
0|BOT  | Error: Cannot find module '/root/raganork-md/node_modules/cache-manager/dist/index.js'. Please verify that the package.json has a valid "main" entry
0|BOT  |     at tryPackage (node:internal/modules/cjs/loader:438:19)
0|BOT  |     at Module._findPath (node:internal/modules/cjs/loader:680:18)
0|BOT  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
0|BOT  |     at Hook._require.Module.require (/root/raganork-md/node_modules/require-in-the-middle/index.js:81:25)
0|BOT  |     at require (node:internal/modules/cjs/helpers:121:18)
0|BOT  |     at Object.<anonymous> (/root/raganork-md/node_modules/@whiskeysockets/baileys/lib/Store/make-cache-manager-store.js:6:25)
0|BOT  |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
0|BOT  |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
0|BOT  |     at Module.load (node:internal/modules/cjs/loader:1119:32)
0|BOT  |     at Module._load (node:internal/modules/cjs/loader:960:12) {
0|BOT  |   code: 'MODULE_NOT_FOUND',
0|BOT  |   path: '/root/raganork-md/node_modules/cache-manager/package.json',
0|BOT  |   requestPath: 'cache-manager'
0|BOT  | }
^X^X^C

**Comment by chocolaid** [comment]
The issue was from the cache-manager module

in package.json  replace `"cache-manager": "^4.0.1",` with `"cache-manager": "4.0.1",`

Or use `npm i cache-manager@4.0.1 --force` because for some reason the developer of the package stopped uploading the index.js of the module making it have an issue 

after adding the module you should run this
`cp -r node_modules/cache-manager node_modules/@whiskeysockets/baileys/node_modules/`

this is because the `@whiskeysockets/baileys` module uses this same cache-manager library so sending a copy of the new cache-manager library there will fix the issue


......Thanks

**Comment by chocolaid** [comment]
`Took me an hour to figure this out hahaha hah.....`

**Comment by chocolaid** [comment]
@souravkl11
