### ISSUE TITLE
The damn YouTube module that causes constant crashes ⛔

### ISSUE THREAD

**Issue by byadems** [souravkl11/raganork-md#244]
This problem often occurs whenever we try to download a song and causes the Bot to crash constantly. I also asked LuanRT, your YouTube library is very old, you should update it immediately, he said. Are you going to fix the problem, man?

```
InnertubeError: SearchHeader not found!

This is a bug, want to help us fix it? Follow the instructions at https://github.com/LuanRT/YouTube.js/blob/main/docs/updating-the-parser.md or report it at https://github.com/LuanRT/YouTube.js/issues!

at Parser._Parser_printError (/railway/Raganork/node_modules/youtubei.js/dist/src/parser/index.js:299:29)

at Parser.parseItem (/railway/Raganork/node_modules/youtubei.js/dist/src/parser/index.js:161:77)

at Parser.parse (/railway/Raganork/node_modules/youtubei.js/dist/src/parser/index.js:205:53)

at Parser.parseResponse (/railway/Raganork/node_modules/youtubei.js/dist/src/parser/index.js:71:45)

at new Feed (/railway/Raganork/node_modules/youtubei.js/dist/src/core/Feed.js:83:70)

at new Search (/railway/Raganork/node_modules/youtubei.js/dist/src/parser/youtube/Search.js:25:9)

at Innertube.<anonymous> (/railway/Raganork/node_modules/youtubei.js/dist/src/Innertube.js:90:20)

at Generator.next (<anonymous>)

at fulfilled (/railway/Raganork/node_modules/youtubei.js/dist/src/Innertube.js:5:58)

at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {

info: {

chipBar: { chipCloudRenderer: [Object] },

searchFilterButton: { buttonRenderer: [Object] },

trackingParams: 'CBAQiOoKIhMIos7CkZ6uhAMVfEtMCB0yWQ3M'

},

date: 2024-02-15T20:58:04.540Z,

```

**Comment by souravkl11** [comment]
I'mma change this lib lol. It requires to be up to date with this module as it used inner api of YouTube ig. As there are no project updates scheduled before April, it'll be fixed in the next patch, and more future issues from your side will be considered as spam. The the project is inactive coz of my exams.

**Comment by souravkl11** [comment]
And, avoid contacting dependency devs before asking here. It may be irritating to them 😹.
